#!/usr/bin/env bash

DOCKER=podman
which docker > /dev/null && DOCKER=docker

build() {
    pushd $1 > /dev/null
    local tmp_img=$1-tmp
    local image=tnairav/$1
    local tag=latest
    local dockerfile=Dockerfile
    if [ -n "$2" ]
    then
        tag=$2
        dockerfile=Dockerfile.$tag
    fi

    docker build --no-cache --squash -t $tmp_img --network=host -f $dockerfile  .
    docker tag $tmp_img $image:$tag
    docker rmi -f $tmp_img
    docker push $image:$tag
    popd > /dev/null
}

build ubuntu-build
build ubuntu-node
build ubuntu-node 13
build ubuntu-node-12
build ubuntu-node-13
build ubuntu-python
build ubuntu-build-non-root
build ubuntu-tarantool
