FROM ubuntu:16.04

USER root
ENV HOME                /root

RUN  apt update && apt upgrade --yes && apt install --yes g++ gcc libc6-dev libffi-dev libgmp-dev make xz-utils zlib1g-dev git gnupg netbase

